export {default as Navbar} from './Navbar/Navbar'
export {default as MajorSection} from './Section/MajorSection'
export {default as SubSection} from './Section/SubSection'
export {default as Footer} from './Footer/Footer'
export {default as ProductCards} from './ProductCards/ProductCards'